# Generated by Django 4.0.4 on 2022-06-01 09:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_teacher_student_teacher_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='teacher_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teacher', to='student.teacher'),
        ),
    ]
